In [16]:
import torch 
import torch.nn as nn 
"""
#tensor = array 
my_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] #3x3 
a = torch.tensor(my_list)
print(a.shape)
print(a.dtype)
print(a @ a)
"""


'\n#tensor = array \nmy_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] #3x3 \na = torch.tensor(my_list)\nprint(a.shape)\nprint(a.dtype)\nprint(a @ a)\n'

In [ ]:
#input layer (number of neurons in input = # of features in dataset)
input_tensor = torch.tensor(
    [[1.2, 2.2, 3.3333, 5.333, 3.2, 6.3, 7.3, 8.3, 9.2, 10.22]] # 3 neurons in input layer
)
'''
#linear layer 
linear_layer = nn.Linear(
    in_features = 3, # have to be correct to pass through 
    out_features = 2 ) # input * weights + bias = output W*x + b
#passing through linear layer 
output = linear_layer(input_tensor)
print(output)

print(linear_layer.weight)
print(linear_layer.bias)
'''

'\n#linear layer \nlinear_layer = nn.Linear(\n    in_features = 3, # have to be correct to pass through \n    out_features = 2 ) # input * weights + bias = output W*x + b\n#passing through linear layer \noutput = linear_layer(input_tensor)\nprint(output)\n\nprint(linear_layer.weight)\nprint(linear_layer.bias)\n'

In [ ]:
'''
[[1.2, 2.2, 3.3333, 5.333, 3.2, 6.3, 7.3, 8.3, 9.2, 10.22]] # 10 neurons in input layer

'''
#Creating more hidden layers & forward pass
model = nn.Sequential(
    nn.Linear(10,5), #1st hidden layer = 5 (11*5 = 55 parameters)
    nn.Linear(5,1), #2nd hidden layer = 1 (6 * 1)
    #nn.Sigmoid()
    #nn.Sigmoid() #binary classification 
    #nn.Softmax() #multiclass classification
)

#total = 61 parameters 
total = 0    
#number of parameters 
for p in model.parameters():
    total += p.numel()
print(total)

#activation functions for classification
sigmoid = nn.Sigmoid()
probability = sigmoid(input_tensor)

softmax = nn.Softmax()
probability2 = softmax(input_tensor)

print(probability)
print(probability2)

output = model(input_tensor)
print(output)


61
tensor([[0.7685, 0.9002, 0.9656, 0.9952, 0.9608, 0.9982, 0.9993, 0.9998, 0.9999,
         1.0000]])
tensor([[7.6037e-05, 2.0669e-04, 6.4196e-04, 4.7420e-03, 5.6184e-04, 1.2472e-02,
         3.3902e-02, 9.2154e-02, 2.2666e-01, 6.2858e-01]])
tensor([[0.2498]], grad_fn=<SigmoidBackward0>)


/Users/minwoongyoon/Documents/Res/.venv/lib/python3.9/site-packages/torch/nn/modules/module.py:1773: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  return self._call_impl(*args, **kwargs)


In [ ]:
#prediction loss function
#one-hot encoding to convert y to a tensor of zeros and ones: ground truth 
from torch.nn import CrossEntropyLoss
y=[1]

#loss function: before the final activation function 
#loss = F(y, y') y' is prediction value y is truth 
#loss function outputs loss - a float 
criterion = CrossEntropyLoss()
#loss = criterion(pred, target)
#loss.backward()



CrossEntropyLoss()


In [ ]:
#backprop e.g. gradient descent, mle/optimizers
import torch.optim
#optimizer SGD: finding minimum error function 
optimizer = torch.optim(model.parameters(), lr= 0.001)
#loss = criterion(pred, target) #cross-entropy
#loss.backward()
optimizer.step()

In [ ]:
import pandas as pd 
import numpy as np 
import torch 
from torch.utils.data import TensorDataset #to store x, y as tensors
from torch.utils.data import DataLoader

#animal data
df = pd.read_csv('OlympicTV.csv')
features = df.iloc[:, 1: -1 ]

X = features.to_numpy()
print(X)

#class label for each animal
target = df.iloc[:, -1]
Y = target.to_numpy()
print(Y)

#x,y to tensor
dataset = TensorDataset(torch.tensor(X), torch.tensor(Y))

batch_size = 2
shuffle = True 

dataloader = DataLoader(dataset, batch_size=batch_size, shuffle=shuffle)

#Iterate over dataloader 
for batch_inputs, batch_labels in dataloader: 
    print(batch_inputs)
    print(batch_labels)

[[0]
 [1]
 [1]
 [2]
 [2]]
[0 0 1 1 2]
tensor([[1],
        [1]])
tensor([1, 0])
tensor([[2],
        [0]])
tensor([2, 0])
tensor([[2]])
tensor([1])


In [ ]:
'''
#Training Loop 
# 1. Loop over the number of epochs and the dataloader
for i in range(num_epochs):
  for data in dataloader:
    
    # 2. Set the gradients to zero
    optimizer.zero_grad()
    
    # 3. Run a forward pass
    feature, target = data
    prediction = model(feature)    
    
    # 4. Compute the loss
    loss = criterion(prediction, target)    
    
    # 5. Compute the gradients
    loss.backward()
    
    # 6. Update the model's parameters
    optimizer.step()

show_results(model, dataloader)
'''

In [ ]:
#activation functions 
'''
nn.ReLU()
leaky_relu = nn.LeakyReLU(negative_slope = 0.05)

relu_pytorch = nn.ReLU()

x_pos = torch.tensor(2.0)
x_neg = torch.tensor(-3.0)

output_pos = relu_pytorch(x_pos)
output_neg = relu_pytorch(x_neg)
'''

Layer Initialization:
Data normalization: scales the input features for stability 
similarly, a layer's weights are initialized to small values - > layer initialization

Transfer Learning: -> same a reduction
instead of randomizaing weights -> reusing a model trained on a first task for a second similar task 
ex. training a model on US army salary - > get weights -> use those weights to train model on EU army salary 

In [ ]:
layer = nn.Linear(64, 128)
print(layer.weight.min(), layer.weight.max()) #initialization the weights to small values to ensure stable outputs
nn.init.uniform_(layer.weight) #pytorch for uniform distribution of initialization
#transfer learning
#to save and load weights 
torch.save(layer, 'layer.pth')
new_layer = torch.load('layer.pth')

#Fine-tuning: type of transfer learning 
#load weights from previously trained model, but train model with a smaller learning rate 
#smaller learning rate & train part of network (freeze) 
for name, param in model.named_parameters(): 
    if name == '0.weight':
        param.requires_grad = False #setting the grad for the first layer as false 

Evaluating the Model: step after training 
- data split into 3 parts
  - train: adjust parameters
  - validation: tunes hyperparameters (lr & momentum)
  - test: evaluates final model performance 
-tracking loss and accuracy during training and validation 

training loss and validation loss helps detect overfitting. 
When model overfits -> train loss decreases but validation loss rise because model becomes used to train data. 
Thus, the same model when trained on the validation dataset, the loss increases as the model has not learned the validation data. 

Loss -> describes how well the model is learning the data: ex. loss = MSE(), 
but not always how acccurately it makes predictions 

so we use accuracy: 
(metric= torchmetric.Accuracy(tasks = "multiclass", num_classes))
metric.update(outputs, labels.argmax(dim=-1)) #we basically keep updating the accuracy for each output (pred), and label (target)
#for the whole epoch 
accuracy = metric.compute()
#reset the metric for the next epoch 
metric.reset()


In [ ]:
'''
#1. Calculate the training loss 
#initialize training loss 
training_loss = 0.0 

for n in epochs: 
    for inputs, labels in trainloader(): 
    
    #forward pass 
    outputs = model(inputs)

    #loss function
    criterion = mean()
    loss = criterion(ouputs, labels)
     
    #backpropagation: gradient descent 
    loss.backward()
    optimizer.step()
    optimizer.zero_grad()

    #calculate and sum the loss
    training_loss += loss.item() #.item() adds each value to total 

epoch_loss = training_loss/len(trainloader) #dividing by number of batches in train loader 

#Calculating Validation Loss 
validation_loss = 0.0 
model.eval() #setting the model to evaluate mode 

with torch.no_grad(): #disable grad. 
    for inputs, labels in validationloader: 
    #forward pass 
        outputs = model(inputs)
    #loss
        loss = criterion(ouputs, labels)
        validation_loss += loss.item()

epoch_loss = validation_loss / len(validationloader)
model.train() #switch back to train mode 
'''

Overfitting
- reduce model size or add dropout layer 
- use weight decay to force parameters to remain small 
- obtain new data or augmenting data 

Regularization: dropout layer
- randomly zeroes out elements of the input tensor during training  
- added after activation
model = nn.Sequential(
    nn.Linear(8, 4),
    nn.ReLU(),
    nn.Dropout(p=0.5) #50% probability of zeroing out elements
)

features = ...
#dropout zeroes out the feature values 

Regularization: weight decay
optimizer = optim.SGD(model.parameters(), lr=0.001, weight_decay=0.0001)
-encourages smaller weights by adding a penalty during optimization 
-reduce overfitting, keeping weights smaller 

Summary

Step 1: Overfit the training set (optimizers like gradient descent)
step 2: reduce overfitting by increasing performance on the validation set (Regularization) Balance training and validation data
Step 3: fine-tune the hyperparameters (lr & momentum) 
random search: 
factor = np.random.uniform(2,6)
lr = 10 ** -factor 
grid search: 
for factor in range(2,6): 
    lr = 10 ** -factor 
